### ISSUE TITLE
Android cannot connect the board

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#11]
Hello,
Now, the two boards can communicate with each other(press button3 and LED1 will blink),but my phone cannot connect to boards,there is no signed-on devices,and I cannot send any interest to boards,either.

**Comment by peurpdapeurp** [comment]
Hello,

I assume you're using the BLE example. It might be that the boards actually do sign on with the phone, but you did not press the "show signed on devices" button in the Android app. You should also make sure that all permissions are enabled for the Android app.

I will be working on improving the Android app's UI soon, so that it is less confusing and more informative as to what the application is actually doing.

**Comment by Heath68** [comment]
I did pressed "show signed on devices" button,but there is no reaction.

**Comment by Heath68** [comment]
And when I debugged new version of BLE example,the two even cannot communicate with each other.

**Comment by peurpdapeurp** [comment]
The examples work for me; I am not sure why they aren't working for you, but it is hard to tell without more details.

I think that this will become more clear after I fix the Android application's UI to be more informative; this should be done by the end of this week.

**Comment by Heath68** [comment]
I downloaded the newest version of NDN-IOT-Android and enabled all permissions of application,now it works well.
