### ISSUE TITLE
nRF5_SDK_15.2.0_9412b96/external/micro-ecc/nrf52hf_armgcc/armgcc/micro_ecc_lib_nrf52.a: No such file or directory

### ISSUE THREAD

**Issue by Heath68** [named-data-iot/ndn-iot-package-over-nordic-sdk#13]
When I build the new version example,this error appeared.

**Comment by peurpdapeurp** [comment]
This is expected behavior; it means that you need to build the micro-ecc library part of the nRF5 SDK by going into the nRF5_SDK_15.2.0_9412b96/external/micro-ecc/nrf52hf_armgcc/armgcc directory and calling "make compile". (i.e., this is unrelated to ndn-lite or any part of the ndn-lite-over-nordic-sdk package)
